import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Save } from "lucide-react";
import { PayrollSettingsApi } from "@/lib/hrPayrollApi";
import PageHeader from "@/components/ui/PageHeader";
import BrandButton from "@/components/ui/BrandButton";
import BrandCard from "@/components/ui/BrandCard";
import { CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";

const componentBlank = { code: "", name_ar: "", name_en: "", category: "earning", calculation_type: "fixed", percentage_base: "base", amount: "", rate: "", minimum_amount: "", maximum_amount: "", rounding_mode: "nearest", is_recurring: true, effective_from: new Date().toISOString().slice(0, 10), effective_to: null, is_social_insurance_base: false, is_taxable: false, show_on_payslip: true, is_active: true, priority: 100 };
const schemeBlank = { scheme_code: "", name_ar: "", name_en: "", employee_rate: "", employer_rate: "", calculation_base: "insurable", minimum_wage: "", maximum_wage: "", effective_from: new Date().toISOString().slice(0, 10), effective_to: null, rounding_mode: "nearest", is_active: true };
const accountFields = [
  ["salary_expense", "مصروف الرواتب"], ["employer_insurance_expense", "مصروف مساهمة صاحب العمل"],
  ["payroll_payable", "الرواتب المستحقة"], ["social_insurance_payable", "الضمان المستحق"],
  ["deductions_payable", "الاقتطاعات المستحقة"], ["employee_advances_receivable", "ذمم سلف الموظفين"], ["cash_bank", "الصندوق / البنك"],
] as const;

export default function PayrollSettings() {
  const { toast } = useToast(); const qc = useQueryClient();
  const query = useQuery({ queryKey: ["payroll-settings"], queryFn: PayrollSettingsApi.get });
  const [componentOpen, setComponentOpen] = useState(false); const [schemeOpen, setSchemeOpen] = useState(false);
  const [component, setComponent] = useState(componentBlank); const [scheme, setScheme] = useState(schemeBlank);
  const [alerts, setAlerts] = useState("7,30,60,90"); const [proration, setProration] = useState("none"); const [accounts, setAccounts] = useState<Record<string, any>>({});
  useEffect(() => { if (!query.data) return; setAlerts((query.data.general?.contract_alert_days ?? []).join(",")); setProration(query.data.general?.proration_policy ?? "none"); setAccounts(query.data.accounts ?? {}); }, [query.data]);
  const refresh = () => void qc.invalidateQueries({ queryKey: ["payroll-settings"] });
  const createComponent = useMutation({ mutationFn: () => PayrollSettingsApi.createComponent({ ...component, amount: component.amount === "" ? null : Number(component.amount), rate: component.rate === "" ? null : Number(component.rate), minimum_amount: component.minimum_amount === "" ? null : Number(component.minimum_amount), maximum_amount: component.maximum_amount === "" ? null : Number(component.maximum_amount) } as any), onSuccess: () => { refresh(); setComponentOpen(false); setComponent(componentBlank); }, onError: (e: Error) => toast({ variant: "destructive", title: "تعذر حفظ المكوّن", description: e.message }) });
  const createScheme = useMutation({ mutationFn: () => PayrollSettingsApi.createScheme({ ...scheme, employee_rate: Number(scheme.employee_rate), employer_rate: Number(scheme.employer_rate), minimum_wage: scheme.minimum_wage === "" ? null : Number(scheme.minimum_wage), maximum_wage: scheme.maximum_wage === "" ? null : Number(scheme.maximum_wage) } as any), onSuccess: () => { refresh(); setSchemeOpen(false); setScheme(schemeBlank); }, onError: (e: Error) => toast({ variant: "destructive", title: "تعذر حفظ نظام الضمان", description: e.message }) });
  const saveGeneral = useMutation({ mutationFn: () => PayrollSettingsApi.updateGeneral({ contract_alert_days: alerts.split(",").map(v => Number(v.trim())).filter(Boolean), proration_policy: proration }), onSuccess: () => toast({ title: "تم حفظ سياسة الرواتب والتنبيهات" }) });
  const saveAccounts = useMutation({ mutationFn: () => PayrollSettingsApi.updateAccounts(Object.fromEntries(accountFields.flatMap(([key]) => [[`${key}_code`, accounts[`${key}_code`]], [`${key}_name`, accounts[`${key}_name`]]]))), onSuccess: () => toast({ title: "تم حفظ ربط الحسابات" }), onError: (e: Error) => toast({ variant: "destructive", title: "تعذر حفظ الحسابات", description: e.message }) });

  if (query.isLoading) return <div className="p-8">جارٍ تحميل إعدادات الرواتب…</div>;
  return <div className="space-y-6" dir="rtl">
    <PageHeader title="إعدادات الرواتب والضمان" subtitle="إعدادات مؤرّخة؛ لا توجد نسب قانونية ثابتة داخل النظام" icon="⚙️" />
    <div className="grid gap-4 lg:grid-cols-2">
      <BrandCard><CardHeader><CardTitle>سياسة الدورة والعقود</CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-1.5"><Label>مدد تنبيه العقد (أيام، مفصولة بفاصلة)</Label><Input value={alerts} onChange={e => setAlerts(e.target.value)} /></div><div className="space-y-1.5"><Label>احتساب التعيين/الإنهاء منتصف الشهر</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={proration} onChange={e => setProration(e.target.value)}><option value="none">دون تجزئة</option><option value="calendar_days">حسب الأيام التقويمية</option></select></div><BrandButton isLoading={saveGeneral.isPending} onClick={() => saveGeneral.mutate()}><Save className="h-4 w-4" /> حفظ السياسة</BrandButton></CardContent></BrandCard>
      <BrandCard><CardHeader className="flex-row items-center justify-between"><CardTitle>أنظمة الضمان المؤرّخة</CardTitle><BrandButton size="sm" onClick={() => setSchemeOpen(true)}><Plus className="h-4 w-4" /> نسخة جديدة</BrandButton></CardHeader><CardContent className="space-y-2">{query.data?.social_insurance_schemes.map(row => <div key={row.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-semibold">{row.name_ar} <span className="text-xs text-muted-foreground">({row.scheme_code})</span></p><p className="text-xs text-muted-foreground">سارية من {row.effective_from}</p></div><div className="text-left text-sm"><div>الموظف {row.employee_rate}%</div><div>صاحب العمل {row.employer_rate}%</div></div></div>)}{!query.data?.social_insurance_schemes.length && <p className="text-sm text-muted-foreground">لا توجد نسب. الموظف المسجل لن يُعالج راتبه حتى تُضاف نسخة سارية.</p>}</CardContent></BrandCard>
    </div>

    <BrandCard><CardHeader className="flex-row items-center justify-between"><CardTitle>مكونات الراتب</CardTitle><BrandButton size="sm" onClick={() => setComponentOpen(true)}><Plus className="h-4 w-4" /> مكوّن</BrandButton></CardHeader><CardContent><div className="grid gap-2 md:grid-cols-2">{query.data?.components.map(row => <div key={row.id} className="rounded-lg border p-3"><div className="flex items-center justify-between"><p className="font-semibold">{row.name_ar}</p><Badge variant="outline">{row.category}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{row.code} · {row.calculation_type === "fixed" ? `مبلغ ${row.amount}` : `نسبة ${row.rate}% من ${row.percentage_base}`} · من {row.effective_from}</p></div>)}</div></CardContent></BrandCard>

    <BrandCard><CardHeader><CardTitle>الربط المحاسبي</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">كل حساب قابل للتعديل؛ تُلتقط الأكواد المستخدمة داخل القيود ولا توجد أرقام داخل Controller.</p><div className="grid gap-3 md:grid-cols-2">{accountFields.map(([key, label]) => <div key={key} className="grid grid-cols-[1fr_2fr] gap-2"><Input aria-label={`${label} code`} value={accounts[`${key}_code`] ?? ""} onChange={e => setAccounts({ ...accounts, [`${key}_code`]: e.target.value })} /><Input aria-label={label} value={accounts[`${key}_name`] ?? ""} onChange={e => setAccounts({ ...accounts, [`${key}_name`]: e.target.value })} /></div>)}</div><BrandButton isLoading={saveAccounts.isPending} onClick={() => saveAccounts.mutate()}><Save className="h-4 w-4" /> حفظ الحسابات</BrandButton></CardContent></BrandCard>

    <Dialog open={componentOpen} onOpenChange={setComponentOpen}><DialogContent dir="rtl"><DialogHeader><DialogTitle>مكوّن راتب مؤرّخ</DialogTitle><DialogDescription>أضف نسخة جديدة عند تغيير القاعدة حتى تبقى الدورات القديمة ثابتة.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2">
      <Field label="الرمز" value={component.code} onChange={value => setComponent({ ...component, code: value })} /><Field label="الاسم العربي" value={component.name_ar} onChange={value => setComponent({ ...component, name_ar: value })} /><Field label="الاسم الإنجليزي" value={component.name_en} onChange={value => setComponent({ ...component, name_en: value })} />
      <SelectField label="التصنيف" value={component.category} onChange={value => setComponent({ ...component, category: value })} options={[["earning", "استحقاق"], ["deduction", "اقتطاع"], ["employer_contribution", "مساهمة صاحب العمل"]]} />
      <SelectField label="طريقة الحساب" value={component.calculation_type} onChange={value => setComponent({ ...component, calculation_type: value })} options={[["fixed", "مبلغ ثابت"], ["percentage", "نسبة"]]} />
      {component.calculation_type === "fixed" ? <Field label="المبلغ" type="number" value={component.amount} onChange={value => setComponent({ ...component, amount: value })} /> : <><Field label="النسبة %" type="number" value={component.rate} onChange={value => setComponent({ ...component, rate: value })} /><SelectField label="أساس النسبة" value={component.percentage_base} onChange={value => setComponent({ ...component, percentage_base: value })} options={[["base", "الأساسي"], ["gross", "الإجمالي"], ["insurable", "الخاضع للضمان"]]} /></>}
      <Field label="الحد الأدنى" type="number" value={component.minimum_amount} onChange={value => setComponent({ ...component, minimum_amount: value })} /><Field label="الحد الأقصى" type="number" value={component.maximum_amount} onChange={value => setComponent({ ...component, maximum_amount: value })} /><Field label="ساري من" type="date" value={component.effective_from} onChange={value => setComponent({ ...component, effective_from: value })} />
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={component.is_social_insurance_base} onChange={e => setComponent({ ...component, is_social_insurance_base: e.target.checked })} /> يدخل في الأجر الخاضع للضمان</label>
    </div><DialogFooter><BrandButton variant="ghost" onClick={() => setComponentOpen(false)}>إلغاء</BrandButton><BrandButton isLoading={createComponent.isPending} onClick={() => createComponent.mutate()}>حفظ النسخة</BrandButton></DialogFooter></DialogContent></Dialog>

    <Dialog open={schemeOpen} onOpenChange={setSchemeOpen}><DialogContent dir="rtl"><DialogHeader><DialogTitle>نسخة نظام ضمان</DialogTitle><DialogDescription>أدخل النسب المعتمدة للبلد والفترة؛ النظام لا يقترح نسبة قانونية.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2">
      <Field label="رمز النظام" value={scheme.scheme_code} onChange={value => setScheme({ ...scheme, scheme_code: value })} /><Field label="الاسم العربي" value={scheme.name_ar} onChange={value => setScheme({ ...scheme, name_ar: value })} /><Field label="الاسم الإنجليزي" value={scheme.name_en} onChange={value => setScheme({ ...scheme, name_en: value })} /><Field label="نسبة الموظف %" type="number" value={scheme.employee_rate} onChange={value => setScheme({ ...scheme, employee_rate: value })} /><Field label="نسبة صاحب العمل %" type="number" value={scheme.employer_rate} onChange={value => setScheme({ ...scheme, employer_rate: value })} /><Field label="ساري من" type="date" value={scheme.effective_from} onChange={value => setScheme({ ...scheme, effective_from: value })} /><Field label="أرضية الأجر" type="number" value={scheme.minimum_wage} onChange={value => setScheme({ ...scheme, minimum_wage: value })} /><Field label="سقف الأجر" type="number" value={scheme.maximum_wage} onChange={value => setScheme({ ...scheme, maximum_wage: value })} />
    </div><DialogFooter><BrandButton variant="ghost" onClick={() => setSchemeOpen(false)}>إلغاء</BrandButton><BrandButton isLoading={createScheme.isPending} onClick={() => createScheme.mutate()}>حفظ النسخة</BrandButton></DialogFooter></DialogContent></Dialog>
  </div>;
}

function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <div className="space-y-1.5"><Label>{label}</Label><Input type={type} value={value} onChange={e => onChange(e.target.value)} /></div>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <div className="space-y-1.5"><Label>{label}</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={value} onChange={e => onChange(e.target.value)}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></div>; }
