<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Receipt {{ $invoice->invoice_no }}</title>
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #222; }
  h1 { font-size: 20px; margin: 0 0 10px; }
  .meta { margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
  th { background: #f0f0f0; }
  .total { font-weight: bold; }
</style>
</head>
<body>
  <h1>Payment Receipt</h1>
  <div class="meta">
    <div><strong>Invoice #:</strong> {{ $invoice->invoice_no }}</div>
    <div><strong>Student:</strong> {{ $invoice->student->name ?? '—' }}</div>
    <div><strong>Description:</strong> {{ $invoice->description }}</div>
    <div><strong>Issued:</strong> {{ $invoice->created_at->format('Y-m-d') }}</div>
    <div><strong>Due:</strong> {{ \Illuminate\Support\Carbon::parse($invoice->due_date)->format('Y-m-d') }}</div>
    <div><strong>Status:</strong> {{ ucfirst($invoice->status) }}</div>
  </div>

  <table>
    <thead><tr><th>Date</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead>
    <tbody>
      @foreach($invoice->payments as $p)
        <tr>
          <td>{{ \Illuminate\Support\Carbon::parse($p->paid_at)->format('Y-m-d H:i') }}</td>
          <td>{{ $p->method }}</td>
          <td>{{ $p->reference ?? '—' }}</td>
          <td>{{ number_format($p->amount, 2) }}</td>
        </tr>
      @endforeach
      <tr class="total">
        <td colspan="3">Total billed</td>
        <td>{{ number_format($invoice->amount, 2) }}</td>
      </tr>
      <tr class="total">
        <td colspan="3">Total paid</td>
        <td>{{ number_format($invoice->paid_amount, 2) }}</td>
      </tr>
      <tr class="total">
        <td colspan="3">Balance</td>
        <td>{{ number_format($invoice->amount - $invoice->paid_amount, 2) }}</td>
      </tr>
    </tbody>
  </table>

  <p style="margin-top: 24px; color: #666;">Thank you. This receipt was generated by the School Management System on {{ now()->format('Y-m-d H:i') }}.</p>
</body>
</html>
