<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Income Statement {{ $year }}-{{ $month }}</title>
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #222; }
  h1 { font-size: 20px; margin: 0 0 10px; }
  .meta { margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
  th { background: #f0f0f0; }
  .total { font-weight: bold; }
</style>
</head>
<body>
  <h1>Income Statement</h1>
  <div class="meta">
    <div><strong>Period:</strong> {{ $year }}-{{ str_pad($month, 2, '0', STR_PAD_LEFT) }}</div>
    <div><strong>Generated:</strong> {{ now()->format('Y-m-d H:i') }}</div>
  </div>

  <table>
    <thead><tr><th>Item</th><th>Amount</th></tr></thead>
    <tbody>
      <tr><td>Total Income</td><td>{{ number_format($total_income, 2) }}</td></tr>
      <tr><td>Total Payroll</td><td>{{ number_format($total_payroll, 2) }}</td></tr>
      <tr><td>Total Expenses</td><td>{{ number_format($total_expenses, 2) }}</td></tr>
      <tr class="total"><td>Net Income</td><td>{{ number_format($net_income, 2) }}</td></tr>
    </tbody>
  </table>

  <p style="margin-top: 24px; color: #666;">Generated by School Management System on {{ now()->format('Y-m-d H:i') }}.</p>
</body>
</html>
