<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Grades Report — Class {{ $classRoomId }} Subject {{ $subjectId }}</title>
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #222; }
  h1 { font-size: 20px; margin: 0 0 10px; }
  .meta { margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
  th { background: #f0f0f0; }
  .total { font-weight: bold; }
</style>
</head>
<body>
  <h1>Grades Report</h1>
  <div class="meta">
    <div><strong>Class ID:</strong> {{ $classRoomId }}</div>
    <div><strong>Subject ID:</strong> {{ $subjectId }}</div>
    <div><strong>Generated:</strong> {{ now()->format('Y-m-d H:i') }}</div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Student Name</th>
        <th>Admission No</th>
        @foreach($componentNames as $name)
          <th>{{ $name }}</th>
        @endforeach
        <th>Total %</th>
      </tr>
    </thead>
    <tbody>
      @foreach($rows as $row)
        <tr>
          <td>{{ $row['name'] }}</td>
          <td>{{ $row['admission_no'] }}</td>
          @foreach($componentNames as $name)
            <td>{{ $row[$name] ?? '—' }}</td>
          @endforeach
          <td class="total">{{ $row['total_pct'] ?? '—' }}%</td>
        </tr>
      @endforeach
    </tbody>
  </table>

  <p style="margin-top: 24px; color: #666;">Generated by School Management System on {{ now()->format('Y-m-d H:i') }}.</p>
</body>
</html>
