<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Trial Balance {{ $year }}-{{ $month }}</title>
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #222; }
  h1 { font-size: 20px; margin: 0 0 10px; }
  .meta { margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
  th { background: #f0f0f0; }
  .total { font-weight: bold; }
</style>
</head>
<body>
  <h1>Trial Balance</h1>
  <div class="meta">
    <div><strong>Period:</strong> {{ $year }}-{{ str_pad($month, 2, '0', STR_PAD_LEFT) }}</div>
    <div><strong>Generated:</strong> {{ now()->format('Y-m-d H:i') }}</div>
  </div>

  <table>
    <thead><tr><th>Account Code</th><th>Account Name</th><th>Total Debit</th><th>Total Credit</th><th>Balance</th></tr></thead>
    <tbody>
      @foreach($rows as $r)
        <tr>
          <td>{{ $r->account_code }}</td>
          <td>{{ $r->account_name }}</td>
          <td>{{ number_format((float) $r->total_debit, 2) }}</td>
          <td>{{ number_format((float) $r->total_credit, 2) }}</td>
          <td>{{ number_format((float) $r->total_debit - (float) $r->total_credit, 2) }}</td>
        </tr>
      @endforeach
    </tbody>
  </table>

  <p style="margin-top: 24px; color: #666;">Generated by School Management System on {{ now()->format('Y-m-d H:i') }}.</p>
</body>
</html>
