<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Inventory Report {{ $date }}</title>
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #222; }
  h1 { font-size: 20px; margin: 0 0 10px; }
  .meta { margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
  th { background: #f0f0f0; }
  .low-stock { color: #c00; font-weight: bold; }
</style>
</head>
<body>
  <h1>Warehouse Inventory Report</h1>
  <div class="meta">
    <div><strong>Date:</strong> {{ $date }}</div>
    <div><strong>Generated:</strong> {{ now()->format('Y-m-d H:i') }}</div>
  </div>

  <table>
    <thead><tr><th>SKU</th><th>Name</th><th>Category</th><th>Unit</th><th>Current Qty</th><th>Min Stock</th><th>Status</th></tr></thead>
    <tbody>
      @foreach($items as $item)
        <tr>
          <td>{{ $item->sku }}</td>
          <td>{{ $item->name }}</td>
          <td>{{ $item->category?->name ?? 'N/A' }}</td>
          <td>{{ $item->unit }}</td>
          <td>{{ number_format((float) $item->current_qty, 2) }}</td>
          <td>{{ number_format((float) $item->min_stock_qty, 2) }}</td>
          <td class="{{ $item->is_low_stock ? 'low-stock' : '' }}">{{ $item->is_low_stock ? 'LOW STOCK' : 'OK' }}</td>
        </tr>
      @endforeach
    </tbody>
  </table>

  <p style="margin-top: 24px; color: #666;">Generated by School Management System on {{ now()->format('Y-m-d H:i') }}.</p>
</body>
</html>
