<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Consumption Report {{ $year }}-{{ $month }}</title>
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #222; }
  h1 { font-size: 20px; margin: 0 0 10px; }
  .meta { margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
  th { background: #f0f0f0; }
</style>
</head>
<body>
  <h1>Warehouse Consumption Report</h1>
  <div class="meta">
    <div><strong>Period:</strong> {{ $year }}-{{ str_pad($month, 2, '0', STR_PAD_LEFT) }}</div>
    <div><strong>Generated:</strong> {{ now()->format('Y-m-d H:i') }}</div>
  </div>

  <table>
    <thead><tr><th>Item Name</th><th>SKU</th><th>Department</th><th>Total Quantity</th><th>Unit</th></tr></thead>
    <tbody>
      @foreach($rows as $r)
        <tr>
          <td>{{ $r->item?->name ?? 'N/A' }}</td>
          <td>{{ $r->item?->sku ?? 'N/A' }}</td>
          <td>{{ $r->department ?? 'N/A' }}</td>
          <td>{{ number_format((float) $r->total_quantity, 2) }}</td>
          <td>{{ $r->item?->unit ?? 'N/A' }}</td>
        </tr>
      @endforeach
    </tbody>
  </table>

  <p style="margin-top: 24px; color: #666;">Generated by School Management System on {{ now()->format('Y-m-d H:i') }}.</p>
</body>
</html>
